apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded AWS credentials
  # echo -n "YOUR_ACCESS_KEY" | base64
  # echo -n "YOUR_SECRET_KEY" | base64
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""