name: SonarCloud

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests and generate coverage report
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
            args: >
              -Dsonar.projectKey=alexandre-mendes_soat-fiap-video-processor-application-ms
              -Dsonar.organization=alexandre-mendes
              -Dsonar.go.coverage.reportPaths=coverage.out
              -Dsonar.exclusions=main.go,cmd/message-processor/main.go,models/video.go,scripts/**,Dockerfile,k8s/**,README.md,services/**,controllers/**,models/**,cmd/**